settings:
  title: 'Natcen Status Page'
  url: 'https://status-page.natcen.ac.uk' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: natcen.ac.uk # unique identifier
    name: natcen.ac.uk
    description: 'Main Natcen Website' # default=empty
    url: 'natcen.ac.uk' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: www-cloudflare-com
    name: www.cloudflare.com
    description: 'Built for anything connected to the Internet.'
    url: 'https://www.cloudflare.com'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: survey.natcen.ac.uk
    description: 'Main Natcen Survey Website'
    name: survey.natcen.ac.uk
    url: 'https://survey.natcen.ac.uk/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: mysurvey.natcen.ac.uk
    description: 'Natcen Survey Website'
    name: mysurvey.natcen.ac.uk
    url: 'https://natcen.ac.uk/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true
    
  - id: bsa.natcen.ac.uk
    description: 'British Social Attitudes Study'
    name: bsa.natcen.ac.uk
    url: 'https://bsa.natcen.ac.uk/'
    method: GET
    expectStatus: 200
    followRedirect: false
    linkable: true

  - id: response_pure360_com # unique identifier
    name: response.pure360.com
    description: 'Pure360's internet routing to their AWS infrastructure' # default=empty
    url: 'response.pure360.com' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true
